name = "Gallery"
license = "MIT"
licenselink = "https://github.com/Sportclub-Schneisingen/hugo-theme-gallery/blob/main/LICENSE"
description = "A very simple and opinionated photo gallery theme for Hugo"
homepage = "https://github.com/Sportclub-Schneisingen/hugo-theme-gallery"
demosite = "https://Sportclub-Schneisingen.github.io/hugo-theme-gallery/"
tags = ["gallery", "responsive", "minimal", "dark"]
min_version = "0.123.0"

[author]
  name = "Janick Lehmann"
  homepage = "https://github.com/janicklehmann"
